### ISSUE TITLE
warning: dotnet new --install is deprecated

### ISSUE THREAD

**Issue by DiFFoZ** [openmod/openmod#705]
![image](https://github.com/openmod/openmod/assets/48765566/d71d5c9a-53fd-4643-bfba-be54e9ca2563)

Need to update the docs to use `dotnet new install`

**Comment by negrifelipe** [comment]
Maybe others don't agree with me but instead of providing a template maybe adding to the documentation how to set up the project from 0 would be a bit better for them to learn how to update the openmod packages and set up the .NET project

**Comment by antjlo** [comment]
also need to remove the "" I believe

**Comment by riku8405** [comment]
> Maybe others don't agree with me but instead of providing a template maybe adding to the documentation how to set up the project from 0 would be a bit better for them to learn how to update the openmod packages and set up the .NET project


It is very easy as visual studio tells you what you need to import when you hover over it and press alt enter, however; this does not work if you manually copy the files from the template which is the reason I couldn't build... Sooo... works fine as long as you use the template, otherwise you don't really know

**Comment by riku8405** [comment]
PR made, please merge. Also need feedback on whether or not removing the "" is a requirement, I believe it is as the "" are only used for `dotnet -i` and not for `dotnet instal`? but need confirmation
