### ISSUE TITLE
Add support for range of frameworks for Unity games

### ISSUE THREAD

**Issue by DiFFoZ** [openmod/openmod#718]
Right now Unturned only support .net461 (or .netstandard2.0), but Unity can support a range of frameworks from net461-net481.

**Comment by CyberAndrii** [comment]
The problem is that the `Environment.Version` property always return version 4.0 for 4.x versions. We will need to use reflection to check if some methods exist and based on that know the version. For example, constructor [`HashSet<T>(Int32, IEqualityComparer<T>)`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1.-ctor?view=net-7.0#system-collections-generic-hashset-1-ctor(system-int32-system-collections-generic-iequalitycomparer((-0)))) was added in 4.7.2. If we can get it via reflection, then this means the runtime version is 4.7.2 or newer.

**Comment by sunnamed434** [comment]
why not just even upgrade the openmod unturned and itself to the net472 😄

**Comment by DiFFoZ** [comment]
I think it just needs to check if runtime is Mono and if it is, then allowing a range from net461-net481, if not then use the old way to get version:
https://github.com/openmod/openmod/blob/main/framework/OpenMod.NuGet/NuGetPackageManager.cs#L108

But still may require to add net481 to the target frameworks

**Comment by CyberAndrii** [comment]
I'm not sure if we can update the target framework because [auto update](https://github.com/openmod/openmod/blob/94e8717cafacd156e662566f307c679dd2e1dd77/unturned/OpenMod.Unturned/Commands/CommandOpenModUpgrade.cs#L109) won't be able to install new packages. Also, I don't think it's a good idea to use or allow to install packages that target 4.8 because it may cause runtime errors like MissingMethodException (I believe Unturned uses 4.7.2).

**Comment by DiFFoZ** [comment]
Just checked what version of framework is using Unity, `2020.3.38f1` (Unturned) uses 4.7.1 and `2021.3.28f1` uses 4.8
