### ISSUE TITLE
"Failed to patch original method null from patching type OpenMod.Unturned.Vehicles.Events.VehiclePatches"

### ISSUE THREAD

**Issue by ItsRodrigoAl** [openmod/openmod#834]
New update, new break XD

Above message is shown when starting the server

**Comment by IlyaSergeevich0** [comment]
Nelson added an overload for `VehicleManager.SpawnVehicleV3` in latest update.

I believe, we should reference this method, since it's a new "entry" method: https://github.com/Unturned-Datamining/Unturned-Datamining/blob/5aad1f52caf66b257b111d607e26ea376c47e755/Assembly-CSharp/SDG.Unturned/VehicleManager.cs#L395C39-L395C53
